---
extends:
  - "@nuxtjs/eslint-config-typescript"
  - plugin:prettier/recommended
rules:
#  no-console: off
  no-tabs: off


# -D -E @nuxtjs/eslint-config-typescript eslint-config-prettier eslint-plugin-prettier prettier eslint