code --install-extension aaron-bond.better-comments
code --install-extension ajshortt.tokyo-hack
code --install-extension alefragnani.project-manager
code --install-extension alexdima.copy-relative-path
code --install-extension atomiks.moonlight
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension bradlc.vscode-tailwindcss
code --install-extension BriteSnow.vscode-toggle-quotes
code --install-extension brittanychiang.halcyon-vscode
code --install-extension christian-kohler.path-intellisense
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension felixfbecker.php-intellisense
code --install-extension fisheva.eva-theme
code --install-extension HookyQR.beautify
code --install-extension jakob101.RelativePath
code --install-extension mgmcdermott.vscode-language-babel
code --install-extension mhutchie.git-graph
code --install-extension mkxml.vscode-filesize
code --install-extension mrmlnc.vscode-scss
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension neilbrayfield.php-docblocker
code --install-extension octref.vetur
code --install-extension praveencrony.total-lines
code --install-extension riseledger.rem-px
code --install-extension ritwickdey.LiveServer
code --install-extension RobbOwen.synthwave-vscode
code --install-extension sleistner.vscode-fileutils
code --install-extension softwaredotcom.swdc-vscode
code --install-extension sysoev.language-stylus
code --install-extension tombonnike.vscode-status-bar-format-toggle
code --install-extension tungvn.wordpress-snippet
code --install-extension vincaslt.highlight-matching-tag
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscode-icons-team.vscode-icons
code --install-extension wesbos.theme-cobalt2
code --install-extension whizkydee.material-palenight-theme
code --install-extension wix.vscode-import-cost
code --install-extension xabikos.JavaScriptSnippets
code --install-extension yzhang.markdown-all-in-one